---
# path: roles/common/tasks/auditd_setup.yml

- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    update_cache: yes

- name: 'Transfer relavent rules for {{ ansible_hostname }}'
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/etc/audit/rules.d'
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - 'files/*.rules'

- name: Reload audit rules
  ansible.builtin.command: 'augenrules --load'
  changed_when: false
