---
# path: roles/commmon/tasks/locale_setup.yml

- name: Configure system locale and keyboard layout
  block:
      # TODO: Add a condition and handler to check keymap
      # integrity and compatibility before loading.
    - name: Extract keyboard mappings
      ansible.builtin.unarchive:
        src: '{{ kbd_url }}'
        dest: '/usr/share'
        remote_src: true
        extra_opts:
          - '--strip-components=2'
          - 'kbd-2.5.1/data/keymaps'
        mode: '0755'

    - name: Configure system locale
      ansible.builtin.command:
        cmd: 'localectl set-locale {{ system_locale.locale }}'

    - name: Configure console keyboard layout
      ansible.builtin.command:
        cmd: 'localectl set-keymap --no-convert {{ system_locale.console_keymap }}'

- name: Set timezone
  community.general.timezone:
    name: '{{ timezone }}'
