---
# Path: roles/monitoring/tasks/auditd.yml

- name: Install the auditd service
  block:
    - name: Get list of installed packages
      ansible.builtin.package_facts:
      manager: auto

    - name: Install auditd
      ansible.builtin.apt:
        name: auditd
        state: present

    - name: Copy audit rules
      ansible.builtin.copy:
        src: "audit.rules"
        dest: "/etc/audit/rules.d/cq-audit.rules"
      notify:

  tags:
    - install_auditd
