services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ZBX_ENABLE_SNMP_TRAPS: "true"
      PGID: 1000
      PUID: 1000
    volumes:
     - /etc/timezone:/etc/timezone:ro
    depends_on:
      - zabbix-db
    ports:
      - "10051:10051"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PHP_TZ: ${PHP_TZ}
      ZBX_SERVER_HOST: zabbix-server
      PGID: 1000
      PUID: 1000
    volumes:
     - /etc/timezone:/etc/timezone:ro
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    restart: unless-stopped

  zabbix-db:
    image: postgres:15
    container_name: zabbix-db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGID: 1000
      PUID: 1000
    volumes:
      - ./db/zbx_db_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

  snmp-trap:
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: zabbix-snmptraps
    ports:
      - "162:162/udp"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      PGID: 1000
      PUID: 1000
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./config/snmp/mibs:/var/lib/zabbix/mibs:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
volumes:
  snmptraps:
    driver: local
