---
# path:/roles/monitoring/tasks/compose_dplyment.yml

- block:
    - name: Start application services using Docker Compose
      community.docker.docker_compose:
        project_src: 'files'
        files: '{{ item }}'
      loop:
        - nginx-pm-docker-compose.yml
        - wazuh-docker-compose.yml
        - zabbix-docker-compose.yml
        - zeek-docker-compose.yml
