---
# path: roles/monitoring/tasks/docker_setup.yml

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto
  changed_when: false

- name: Check whether Docker is installed
  ansible.builtin.debug:
    var: 'ansible_facts.packages["docker-ce"]'
  when: '"docker-ce" in ansible_facts.packages'
  register: is_installed
  changed_when: false

- block:
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - 'ca-certificates'
          - 'curl'
          - 'gnupg-agent'
          - 'software-properties-common'
          - 'python3-venv'
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        state: present
      args:
        creates: '/etc/apt/trusted.gpg.d/docker-archive-keyring.gpg'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: 'deb https://download.docker.com/linux/{{ ansible_facts["os_family"]|lower }} 
                {{ ansible_distribution_release }} stable'

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'
        state: latest

    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: 'https://github.com/docker/compose/releases/download/v{{ compose.version
          }}/docker-compose-linux-{{ ansible_architecture }}'
        dest: '/usr/local/bin/docker-compose'
        mode: '0755'
        checksum: '{{ compose.checksum }}'
  when: 'not is_installed is defined or not is_installed'
  any_errors_fatal: true

