---
# path: playbooks/beelzebub.yml

- hosts: beelzebub
  become: true
  vars_files:
    - ../inventories/beelzebub/host_vars/vars.yml
    - ../inventories/group_vars/main.yml
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - common
    - desktop
