---
# path: roles/monitoring/files/npm-docker-compose.yml

networks:
  nginx-proxy-manager:
    driver: bridge
    name: nginx-proxy-manager

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2'
    restart: unless-stopped
    container_name: nginx-proxy-manager

    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - './cert:/etc/nginx/certs:ro'
      - './config/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - nginx-proxy-manager

    resources:
      limits:
        memory: '2G'
        cpus: '1.0'
      reservations:
        memory: '512M'

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
