---
# Path: roles/commmon/tasks/access-control-settings.yml

- name: Generate sshd defaults configuration file
  ansible.builtin.template:
    src: Defaults.j2
    dest: /etc/ssh/sshd_config.d/Defaults.conf
    owner: root
    group: root
    mode: "0640"
  notify: restart systemd ssh service
  tags:
    - gen-ssh-conf

- name: Generate sudo defaults configuration file
  ansible.builtin.template:
    src: sudoDefaults.j2
    dest: /etc/sudoers.d/Defaults
    owner: root
    group: root
    mode: "0440"
  notify:
    - validate sudo configuration
  tags:
    - gen-sudo-conf


- name: Configure necessary sudoers access
  community.general.sudoers:
    name: "{{ local_ }}"
