services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    group_add:
      - "993" # Render
      - "44"  # Video
    restart: no
    volumes:
      - /mnt/hgst/docker/jellyfin/etc:/etc/jellyfin
      - /mnt/hgst/docker/jellyfin/var-lib:/var/lib/jellyfin
      - /mnt/hgst/docker/jellyfin/var-log:/var/log/jellyfin
      - /mnt/hgst/media:/media
      - /dev/shm:/var/cache/jellyfin:rw
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
#    networks:
#      proxy:
#        aliases:
#          - jellyfin
    ports:
      - "8096:8096"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    restart: no
    volumes:
      - /mnt/hgst/docker/bazarr:/config
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    depends_on:
      - sonarr
      - radarr
    networks:
      proxy:
        aliases:
          - bazarr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    restart: no
    volumes:
      - /mnt/hgst/docker/jellyseerr:/app/config
    environment:
      - TZ=Europe/London
    depends_on:
      - sonarr
      - radarr
    networks:
      proxy:
        aliases:
          - jellyseerr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: no
    volumes:
      - /mnt/hgst/docker/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    depends_on:
      - flaresolverr
    networks:
      proxy:
        aliases:
          - prowlarr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    restart: no
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      proxy:
        aliases:
          - flaresolverr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: no
    volumes:
      - /mnt/hgst/docker/radarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    depends_on:
      - prowlarr
      - jellyfin
    networks:
      proxy:
        aliases:
          - radarr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: no
    volumes:
      - /mnt/hgst/docker/sonarr:/config
    environment:
      - TZ=Europe/London
    depends_on:
      - prowlarr
      - jellyfin
    networks:
      proxy:
        aliases:
          - sonarr
networks:
  proxy:
    external: true
