---

networks:
  nginx-proxy:
    external: true

x-logging: &default-logging
  logging:
    driver: 'json-file'
    options:
      max-size: '10m'
      max-file: '3'

#-----------JELLYFIN--------------#
services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped 

    container_name: jellyfin
    hostname: jellyfin

    volumes:
      - '${JELLYFIN_DATA}:/data'
      - '${JELLYFIN_CONFIG}:/config'
      - '${JELLYFIN_MEDIA}:/media'
      - '/dev/shm:/cache/jellyfin:rw'
    env_file:
      - '.env'
    environment:
      - 'JELLYFIN_CACHE_DIR=/var/cache/jellyfin'
      - 'JELLYFIN_CONFIG_DIR=/etc/jellyfin'
      - 'JELLYFIN_DATA_DIR=/var/lib/jellyfin'
      - 'JELLYFIN_LOG_DIR=/var/log/jellyfin'
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card0
    expose:
      - '8096:8096'
    networks:
      nginx-proxy:
        aliases:
          - jellyfin
#---------------------------------#

#--------------BAZARR-------------#
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    restart: no

    container_name: bazarr
    hostname: bazarr

    volumes:
      - ${BAZARR_DATA}:/data
      - ${BAZARR_CONFIG}:/config
    env_file:
      - .env
    depends_on:
      - sonarr
      - radarr
    expose: 
      - '6767:6767' 
    networks:
      nginx-proxy:
        aliases:
          - bazarr

    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
#---------------------------------#

#-------------PROWLARR------------#
  prowlarr:
    image: linuxserver/prowlarr:latest
    restart: no

    container_name: prowlarr
    hostname: prowlarr

    volumes:
      - ${PROWLARR_DATA}:/data
      - ${PROWLARR_CONFIG}:/config
    env_file:
      - .env
    depends_on:
      - flaresolverr
    expose:
      - '8096:8096'
    networks:
      nginx-proxy:
        aliases:
          - prowlarr

    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
#---------------------------------#

#----------FLARESOLVERR-----------#
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: no

    container_name: flaresolverr
    hostname: flaresolverr

    volumes:
      - ${FLARESOLVERR_DATA}:/data
      - ${FLARESOLVERR_CONFIG}:/config
    env_file:
      - .env
    environment:
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    expose:
      - '9696:9696'
    networks:
      nginx-proxy:
        aliases:
          - flaresolverr

    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
#---------------------------------#

#--------------RADARR-------------#
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: no

    container_name: radarr
    hostname: radarr

    volumes:
      - ${RADARR_DATA}:/data
      - ${RADARR_CONFIG}:/config
    env_file:
      - .env
    depends_on:
      - prowlarr
      - jellyfin
    expose:
      - '7878:7878'
    networks:
      nginx-proxy:
        aliases:
          - radarr

    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
#---------------------------------#

#--------------SONARR-------------#
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: no

    container_name: sonarr
    hostname: sonarr

    volumes:
      - ${SONARR_DATA}:/data
      - ${SONARR_CONFIG}:/config
    env_file:
      - .env
    depends_on:
      - prowlarr
      - jellyfin
    expose:
      - '8989:8989'
    networks:
      nginx-proxy:
        aliases:
          - sonarr

    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1.0
#---------------------------------#
